### ISSUE TITLE
guards and hooks

### ISSUE THREAD

**Issue by darscan** [pixels4nickels/robotlegs-extensions-SignalCommandMap#1]
Guards and hooks are implemented as package level functions now. You can reference the EventCommandMap:

https://github.com/robotlegs/robotlegs-framework/blob/version2/src/robotlegs/bender/extensions/eventCommandMap/impl/EventCommandTrigger.as#L118

Specifically:

```
if (guardsApprove(mapping.guards, _injector))
```

And:

```
applyHooks(mapping.hooks, _injector);
```

That should do it :)

**Comment by pixels4nickels** [comment]
Nice! this is exactly what I was working on and was about to ask for some guidance. Looking really good man.
