### ISSUE TITLE
Latest changes to Robotlegs 2 causes missing mapping exception

### ISSUE THREAD

**Issue by peterkeating** [pixels4nickels/robotlegs-extensions-SignalCommandMap#10]
The latest changes pushed to the version2 branch of Robotlegs caused my example application (https://github.com/peterkeating/todolist-example) to throw an exception when defining the mapping of a Signal to a Command. The exception is saying that a mapping can't be found for the Signal and no fallback provider has been set on the Injector. 

Looking through the [recent changes](https://github.com/Stray/SwiftSuspenders/commits/master) @Stray has made to Robotlegs / SwiftSuspenders it appears that the Injector will no longer create an instance of an object if a mapping doesn't exist. The simple fix is to set the fallbackProvider property on the Injector as a new FreshInstanceProvider as specified in the [documentation](https://github.com/Stray/SwiftSuspenders/blob/ef413d5dc982a10a4724db5021be4b392019d5be/fallbackProviders.md)  that Stray provided. This could easily be done in the constructor for the SignalCommandMap class.

I was going to make these changes and submit a pull request but then thought was this the right way to do things? Stray stated "Missing Mappings are usually a mistake....", so should the signal mapping be specified outside of the SignalCommadMap.map().toCommand() ? So the SignalCommandMap no longer handles the mapping of the signal and only maps the signal to the command?

Thoughts?

**Comment by Stray** [comment]
Thanks for this - there's just one place where you need to make a change - lines 157 and 158 of the SignalCommandTrigger currently read:

```
    _signal = _injector.getInstance( _signalClass );
    _injector.map( _signalClass).toValue( _signal );
```

Instead they now need to read

```
    _injector.map( _signalClass).asSingleton();
    _signal = _injector.getInstance( _signalClass );
```

That should do it - but I'll wait for your confirmation...

Sx

**Comment by Stray** [comment]
I just realised you don't necessarily own this repo... I've just forked and will fix and send a pull request.

**Comment by peterkeating** [comment]
Perfect, was going to do the pull request myself but you beat me to it :)
