### ISSUE TITLE
Chained signals with value objects can throw errors

### ISSUE THREAD

**Issue by alecmce** [pixels4nickels/robotlegs-extensions-SignalCommandMap#15]
If you look at the unit-test in my branch: http://bit.ly/YPzyce, you should get the idea. I'm currently committed to using a slightly older version of RobotLegs 2, so don't want to refresh my branch with the latest directly. If you merge http://bit.ly/YPzZTD into your branch and deal with the conflicts, it will resolve the problem.

Regards,
Alec

**Comment by pixels4nickels** [comment]
Great catch, Alec.  I merged and tested this today and everything seems to be in order. Thanks again for your contributions.  I am working in the city again. Maybe we can catch a beer sometime.
Cheers,
Ken

**Comment by alecmce** [comment]
Hi Ken,

Sure! I'd love to have a beer sometime. This week is a bit manic for me as I'm only just back from the UK and my wife's flying in tomorrow, but next week perhaps?
