### ISSUE TITLE
RL contributors team

### ISSUE THREAD

**Issue by creynders** [pixels4nickels/robotlegs-extensions-SignalCommandMap#19]
Hi @pixels4nickels probably you already received an invite for the RL contributors team. The idea is to consolidate the RL extensions and examples into this. Would you be interested in either: 1/ creating a fork of your SCM repo to the RL contributors
or
2/ transferring ownership of your SCM repo to RL contributors?

Whatever you deem easiest. If you're interested in joining obviously.

**Comment by pixels4nickels** [comment]
I have not received an invite(that I can see). Where should I be seing this?

**Comment by creynders** [comment]
Hmmm... Normally you should've received an e-mail that you've been added to
the contrib team. Are you able to switch persona to the RL org?

On Thursday, May 30, 2013, Ken Rogers wrote:

> I have not received an invite(that I can see). Where should I be seing
> this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pixels4nickels/robotlegs-extensions-SignalCommandMap/issues/19#issuecomment-18684917
> .

## 

Sent from Gmail Mobile

**Comment by pixels4nickels** [comment]
I am not sure exactly what u mean to switch persona to RL org. I would like
to join and fork though. Thanks!

**Comment by creynders** [comment]
[I forked it for you.](https://github.com/robotlegs/robotlegs-extensions-SignalCommandMap) I must confess it's all a little non-transparent though.
Normally you should be able to push and pull to it now.

From now on if I do updates to reflect the RL API changes, I'll push them to the fork. Maybe you should add a "official repo at..." in the description of your repo.

**Comment by pixels4nickels** [comment]
okay looks like we are set!
