### ISSUE TITLE
Mapping multiple command to a single signal doesn't work

### ISSUE THREAD

**Issue by quentint** [pixels4nickels/robotlegs-extensions-SignalCommandMap#3]
When I map multiple commands to a single signal, the first command is executed properly but the following ones are never executed, but the first one is, again!

Here's some sample code:

```
commandMap.map(AuthenticationRequested).toCommand(TryAuthentication);           // This works
commandMap.map(AuthenticateSuccessSignal).toCommand(StoreActiveUser);           // This works
commandMap.map(AuthenticateSuccessSignal).toCommand(LoadUserMedias);            // This doesn't work, StoreActiveUser is executed instead
commandMap.map(AuthenticateSuccessSignal).toCommand(StoreAvailableLanguages);   // This doesn't work, StoreActiveUser is executed instead
```

Hope you can fix it, because this extension is a must-have (at least to me)!

**Comment by pixels4nickels** [comment]
Thanks for the report!  I am updating this for the latest changes in RL2
and will fix this as well.

best,
Ken

On Mon, May 7, 2012 at 8:30 AM, Quentin <
reply@reply.github.com

**Comment by pixels4nickels** [comment]
I am not so sure this will be an easy thing to support. I would recommend that you map to a macro command and execute your individual commands from there.  I am still going to see if I can address.

**Comment by quentint** [comment]
I understand, but I really thing this is a must-have feature.
The RL1 version worked this way!

Easier to say than to implement, I know...

**Comment by pixels4nickels** [comment]
I based this off of Joel's library so I will do my best to port all features :)

**Comment by pixels4nickels** [comment]
This has been added

**Comment by quentint** [comment]
Works like a charm.
Thanks!

**Comment by quentint** [comment]
I can't find a simple way to demonstrate it, but it seems like the commands aren't always executed in the order they've been mapped. Not random (as it always behaves the same), but unpredictable!

Experienced it, too?

**Comment by pixels4nickels** [comment]
Hey Quintin,

There is no work done to pay attention to the order of mapping.  This is
another good reason to use macro commands.  Macro commands will allow you
to decide the order as well as deal with any asynchronous behavior that may
be desired.  I lost all my unit tests and have been working to get them
rewritten and checked in.  While doing so I will take a look at the way we
store and order things. Not making any promises just yet :)

I hope to have the unit tests checked in later today.

Best,
Ken

On Tue, May 22, 2012 at 8:25 AM, Quentin <
reply@reply.github.com

**Comment by quentint** [comment]
Oh, I see!
Are you speaking of Macrobot macro commands? If so, I never tried them, but
I surely will!

Thanks!

Quentin.
http://toki-woki.net

On Tue, May 22, 2012 at 6:29 PM, Ken Rogers <
reply@reply.github.com

**Comment by pixels4nickels** [comment]
I like to use a (extend) MacroCommand class.  It let's me declare a bunch
of commands that I want "chained" together. When I execute that command, it
executes each command registered in sequence.  A good macro command class
will also let you either execute them in an order one after another, or
wait for callback before moving on to the next one, allowing for some or
all of them do perform async behavior.

I jsut took a look at the macrobot stuff you mentioned and yes, that is
exactly the pattern I am talking about:
http://aaronhardy.com/flex/macrobot-macro-commands-for-robotlegs/

Let me know if need any further guidance. I will be in the #flex and #haxe
IRC today on freenode

Best,
Ken

On Tue, May 22, 2012 at 9:35 AM, Quentin <
reply@reply.github.com

**Comment by pixels4nickels** [comment]
I am going to write up a new MacroCommand that does not use events. I will let you know when it is available Quinten.

**Comment by quentint** [comment]
Very cool, thanks!
