### ISSUE TITLE
Update to latest RL2

### ISSUE THREAD

**Issue by darscan** [pixels4nickels/robotlegs-extensions-SignalCommandMap#4]
Hello, just to let you know, the extension mechanism in RL2 has changed a bit, so this extension probably needs updating.

**Comment by pixels4nickels** [comment]
Thanks man :)
I will be working that out this week and will update the Git as well as add
the unit tests.

best,
Ken

On Mon, May 7, 2012 at 8:45 AM, Shaun Smith <
reply@reply.github.com

**Comment by katopz** [comment]
looking fwd to this! thanks both of you! :D

**Comment by pixels4nickels** [comment]
Extension is updated...unit tests on the way.

**Comment by quentint** [comment]
Only thing missing I found: IContextExtension needs to be changed to IExtension, to match RL2's latest changes.
